### ISSUE TITLE
报错Traceback (most recent call last):   File "laowang.py", line 22, in <module>     from lxml import etree ModuleNotFoundError: No module named 'lxml'。linux有这个依赖

### ISSUE THREAD

**Issue by earl1193** [jzjbyq/AutoCheckIn#1]
报错Traceback (most recent call last):   File "laowang.py", line 22, in <module>     from lxml import etree ModuleNotFoundError: No module named 'lxml'。linux有这个依赖

**Comment by suyeonku** [comment]
用的是青龙吗，我尝试过2.12的青龙安装不上依赖，但是2.15.7的青龙装上了

**Comment by jzjbyq** [comment]
> 

青龙面板中可安装依赖，如果是云函数 使用 "python3 pip -m install lxml" 进行安装

**Comment by earl1193** [comment]
raceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fe0f1cc2f10>: Failed to establish a new connection: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.laowang555.com', port=443): Max retries exceeded with url: /wp-admin/admin-ajax.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe0f1cc2f10>: Failed to establish a new connection: [Errno 110] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "laowang.py", line 111, in <module>
    handler('', '')
  File "laowang.py", line 106, in handler
    start(_postdata)
  File "laowang.py", line 64, in start
    res = requests.post('https://www.laowang555.com/wp-admin/admin-ajax.php', headers=headers,
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.laowang555.com', port=443): Max retries exceeded with url: /wp-admin/admin-ajax.php (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe0f1cc2f10>: Failed to establish a new connection: [Errno 110] Operation timed out'))

老王的报错
