### ISSUE TITLE
青龙v2.15.7司机社签到失败，从2月16日开始报错，望作者修复一下，感谢

### ISSUE THREAD

**Issue by suyeonku** [jzjbyq/AutoCheckIn#2]
下面是青龙的日志

## 开始执行... 2023-02-18 14:05:23

发现 1 个账号信息

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7ff2c9df74f0>, 'Connection to sijishea.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sijishea.com', port=443): Max retries exceeded with url: /member.php?mod=logging&action=login&frommessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff2c9df74f0>, 'Connection to sijishea.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/sign.py", line 262, in <module>
    handler('', '')
  File "/ql/data/scripts/sign.py", line 257, in handler
    start(_postdata)
  File "/ql/data/scripts/sign.py", line 148, in start
    get_cookie_formhash()
  File "/ql/data/scripts/sign.py", line 84, in get_cookie_formhash
    response = requests.get(main_url + '/member.php?mod=logging&action=login&frommessage')
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='sijishea.com', port=443): Max retries exceeded with url: /member.php?mod=logging&action=login&frommessage (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff2c9df74f0>, 'Connection to sijishea.com timed out. (connect timeout=None)'))

**Comment by suyeonku** [comment]
sijishea.com已被墙

**Comment by jzjbyq** [comment]
网络问题须自行解决

**Comment by jzjbyq** [comment]
> sijishea.com已被墙

sijishea只是比之前访问慢了许多，测试还是可以打开的，不过还是增加了站点切换，现在可以按顺序切换几个备用站点，如果都无法访问，只能自己搭梯子了
