### ISSUE TITLE
司机社报错

### ISSUE THREAD

**Issue by lls8475** [jzjbyq/AutoCheckIn#3]
检测网址 https://sijisheb.com

网址 https://sijisheb.com 有效, 开始签到

发现 1 个账号信息

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='sijisheb.com', port=443): Max retries exceeded with url: /member.php?mod=logging&action=login&frommessage (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))

## 执行结束... 2023-03-14 21:37:02  耗时 18 秒

这个是什么问题？提示发现账号1个，那么说明网络通了，也识别了账号，后面这些报错，我就认识SSL，是https的加密证书的一种
但是这种报错，真看不懂，新手小白，不懂pyhton..... php还好说

**Comment by jzjbyq** [comment]
每天设置2到3次执行，分开时间段，部分网络情况会这样，我22点刚执行的任务没问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月14日(周二) 晚上9:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [jzjbyq/AutoCheckIn] 司机社报错 (Issue #3)




 
检测网址 https://sijisheb.com
 
网址 https://sijisheb.com 有效, 开始签到
 
发现 1 个账号信息
 
Traceback (most recent call last):
 File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
 httplib_response = self._make_request(
 ^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
 self._validate_conn(conn)
 File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in validate_conn
 conn.connect()
 File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 414, in connect
 self.sock = ssl_wrap_socket(
 ^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl.py", line 449, in ssl_wrap_socket
 ssl_sock = ssl_wrap_socket_impl(
 ^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl.py", line 493, in _ssl_wrap_socket_impl
 return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
 return self.sslsocket_class._create(
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/ssl.py", line 1075, in _create
 self.do_handshake()
 File "/usr/local/lib/python3.11/ssl.py", line 1346, in do_handshake
 self._sslobj.do_handshake()
 ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
 File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
 resp = self.send(prep, **send_kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
 r = adapter.send(request, **kwargs)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 563, in send
 raise SSLError(e, request=request)
 requests.exceptions.SSLError: HTTPSConnectionPool(host='sijisheb.com', port=443): Max retries exceeded with url: /member.php?mod=logging&amp;action=login&amp;frommessage (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))
 
执行结束... 2023-03-14 21:37:02  耗时 18 秒
 
这个是什么问题？提示发现账号1个，那么说明网络通了，也识别了账号，后面这些报错，我就认识SSL，是https的加密证书的一种
 但是这种报错，真看不懂，新手小白，不懂pyhton..... php还好说

**Comment by lls8475** [comment]
你意思说，那就多设置几次任务呗，明白了

**Comment by earl1193** [comment]
发布页地址获取失败，正在进行第1/10次重试
发布页地址获取失败，正在进行第2/10次重试
发布页地址获取失败，正在进行第3/10次重试
发布页地址获取失败，正在进行第4/10次重试
发布页地址获取失败，正在进行第5/10次重试
发布页地址获取失败，正在进行第6/10次重试
发布页地址获取失败，正在进行第7/10次重试
发布页地址获取失败，正在进行第8/10次重试
发布页地址获取失败，正在进行第9/10次重试

## 执行结束... 2023-04-10 22:47:25 耗时 92 秒
一直这样重复几次了司机

**Comment by lls8475** [comment]
> 

不用考虑了，我都做了8次任务，不同时段，每天都还要去看看是否成功了
相当低的成功率签到成功！

**Comment by jzjbyq** [comment]
> 发布页地址获取失败，正在进行第1/10次重试 发布页地址获取失败，正在进行第2/10次重试 发布页地址获取失败，正在进行第3/10次重试 发布页地址获取失败，正在进行第4/10次重试 发布页地址获取失败，正在进行第5/10次重试 发布页地址获取失败，正在进行第6/10次重试 发布页地址获取失败，正在进行第7/10次重试 发布页地址获取失败，正在进行第8/10次重试 发布页地址获取失败，正在进行第9/10次重试
> 
> ## 执行结束... 2023-04-10 22:47:25 耗时 92 秒
> 一直这样重复几次了司机

是你那边网路访问发布页异常，可以尝试使用梯子访问
我这边测试访问正常的
